### ISSUE TITLE
Cocoapods release is currently broken

### ISSUE THREAD

**Issue by rchatham** [SYNQfm/SYNQ-Swift#1]
What is the current eta on this reaching 1.0.0?

**Comment by kjartanvest** [comment]
This is an early release, we will add some more features in the next weeks or so. Stay tuned for updates! I will look into the cocoapods issue, can you please describe what went wrong?

**Comment by kjartanvest** [comment]
If you got the error "Unable to find a specification for 'SynqSwift' " when running pod install, your local spec repo might not be up to date. Fix this by running `pod repo update`

The cocoapods website did not display the pod correctly, this happens occasionally when a new pod is added. This has now been fixed. I'm now closing this issue.

**Comment by rchatham** [comment]
Hey sounds good! It looks better now. Thank you.
